4.2 Вложенные списки. Часть 1

Дополните приведенный код, используя списочный метод append(), чтобы список list1 имел вид:

list1 = [10, 20, [300, 400, [5000, 6000, 7000], 500], 30, 40]

In [16]:
list1 = [10, 20, [300, 400, [5000, 6000], 500], 30, 40]
list1[2][2].append(7000)
print(list1)

[10, 20, [300, 400, [5000, 6000, 7000], 500], 30, 40]


Дополните приведенный код, используя списочный метод extend(), чтобы список list1 имел вид:

list1 = ['a', 'b', ['c', ['d', 'e', ['f', 'g', 'h', 'i', 'j'], 'k'], 'l'], 'm', 'n']

Подсписок для расширения  sub_list = ['h', 'i', 'j'].

In [6]:
list1 = ['a', 'b', ['c', ['d', 'e', ['f', 'g'], 'k'], 'l'], 'm', 'n']
sub_list = ['h', 'i', 'j']
list1[2][1][2].extend(sub_list)
print(list1)


['a', 'b', ['c', ['d', 'e', ['f', 'g', 'h', 'i', 'j'], 'k'], 'l'], 'm', 'n']


Дополните приведенный код, используя цикл for и встроенную функцию max(), чтобы он выводил один общий максимальный элемент среди всех элементов вложенных списков list1.

In [62]:
def maximum(my_list: list): # после первого двоеточия идет указания о том, какой тип данных необходим для данной ф-ции 
    return max([max(i) for i in my_list])

list1 = [[1, 7, 8], [9, 7, 102], [6, 106, 105], [100, 99, 98, 103], [1, 2, 3]]
print(maximum(list1))


106


Дополните приведенный код так, чтобы список list1 имел вид:

list1 = [[8, 7, 1], [102, 7, 9], [105, 106, 102], [103, 98, 99, 100], [3, 2, 1]]

In [61]:
def reverse_list(my_list: list): # после первого двоеточия идет указания о том, какой тип данных необходим для данной ф-ции 
    return [i[::-1] for i in my_list]

list1 = [[1, 7, 8], [9, 7, 102], [102, 106, 105], [100, 99, 98, 103], [1, 2, 3]]
print(reverse_list(list1))

[[8, 7, 1], [102, 7, 9], [105, 106, 102], [103, 98, 99, 100], [3, 2, 1]]


Дополните приведенный код так, чтобы он выводил единственное число: сумму всех чисел списка list1 разделённую на общее количество всех чисел.

In [63]:
def middle(my_list: list): # после первого двоеточия идет указания о том, какой тип данных необходим для данной ф-ции 
    total=sum([sum(i) for i in my_list])
    count=sum([len(j) for j in my_list])
    return total/count

list1 = [[1, 7, 8], [9, 7, 102], [102, 106, 105], [100, 99, 98, 103], [1, 2, 3]]
print(middle(list1))

53.3125


4.3 Вложенные списки. Часть 2

Что покажет приведенный ниже фрагмент кода?

list1 = [[1, 2, 3], [4, 5]]</br>
list2 = list1</br>

list1[0].append(7)</br>

print(list2)

In [1]:
list1 = [[1, 2, 3], [4, 5]]
list2 = list1
list1[0].append(7)
print(list2)

[[1, 2, 3, 7], [4, 5]]


Чему будет равно list1[1][1] после выполнения следующего фрагмента кода:

list1 = [[1] * 3] * 3</br>
list1[0][1] = 5

In [2]:
list1 = [[1] * 3] * 3
list1[0][1] = 5
print(list1[1][1])

5


Что покажет приведенный ниже фрагмент кода

n = 3</br>
list1 = []</br>
for _ in range(n):</br>
    row = input().split()</br>
    list1.extend(row)</br>
print(list1)

если на вход программе подаются строки:

9 7 6</br>
2 1</br>
3 4 45 67</br>

In [3]:
n = 3
list1 = []

for _ in range(n):
    row = input().split()
    list1.extend(row)

print(list1)

['9', '7', '6', '2', '1', '3', '4', '45', '67']


Что покажет приведенный ниже фрагмент кода?

my_list = [[12, 221, 3], [41, 5, 633], [71, 8, 99]]</br>
maximum = my_list[0][0]</br>
minimum = my_list[0][0]</br>
for row in my_list:</br>
    maximum = max(row)</br>
    minimum = min(row)</br>
print(maximum + minimum)</br>

In [4]:
my_list = [[12, 221, 3], [41, 5, 633], [71, 8, 99]]
maximum = my_list[0][0]
minimum = my_list[0][0]
for row in my_list:
    maximum = max(row)
    minimum = min(row)
print(maximum + minimum)

107


Что покажет приведенный ниже фрагмент кода?

my_list = [[12, 221, 3], [41, 5, 633], [71, 8, 99]]</br>
maximum = my_list[0][0]</br>
minimum = my_list[0][0]</br>
for row in my_list:</br>
    if max(row) > maximum:</br>
        maximum = max(row)</br>
    if min(row) < minimum:</br>
        minimum = min(row)</br>
print(maximum + minimum)</br>

In [5]:
my_list = [[12, 221, 3], [41, 5, 633], [71, 8, 99]]
maximum = my_list[0][0]
minimum = my_list[0][0]
for row in my_list:
    if max(row) > maximum:
        maximum = max(row)
    if min(row) < minimum:
        minimum = min(row)
print(maximum + minimum)

636


Список по образцу 1

На вход программе подается число n. Напишите программу, которая создает и выводит построчно список, состоящий из n списков [[1, 2, ..., n], [1, 2, ..., n], ..., [1, 2, ..., n]].

Формат входных данных:</br>
На вход программе подается натуральное число n.

Формат выходных данных:</br>
Программа должна вывести построчно указанный список.

In [40]:
x=int(input())
y=[i for i in range(1,x+1)]
for j in range(x):
    print(y)
print()

[1, 2, 3, 4]
[1, 2, 3, 4]
[1, 2, 3, 4]
[1, 2, 3, 4]



In [41]:
#правильное решение от автора курса
n = int(input())
result = []

for _ in range(n):
    result.append(list(range(1, n + 1)))

print(*result, sep='\n')

[1, 2, 3, 4]
[1, 2, 3, 4]
[1, 2, 3, 4]
[1, 2, 3, 4]


Список по образцу 2

На вход программе подается числоиn. Напишите программу, которая создает и выводит построчно вложенный список, состоящий из n списков [[1], [1, 2], [1, 2, 3], ..., [1, 2, ..., n]].

Формат входных данных:</br>
На вход программе подается натуральное число n.

Формат выходных данных:</br>
Программа должна вывести построчно указанный вложенный список.

In [50]:
x=int(input())
z=[]
for i in range(1, x+1):
    y=[i+1 for i in range(i)]
    z.append(y)
print(*z, sep='\n')

[1]
[1, 2]
[1, 2, 3]
[1, 2, 3, 4]


Треугольник Паскаля 1 🌶️

Треугольник Паскаля — бесконечная таблица биномиальных коэффициентов, имеющая треугольную форму. В этом треугольнике на вершине и по бокам стоят единицы. Каждое число равно сумме двух расположенных над ним чисел.

0:      1</br>
1:     1 1</br>
2:    1 2 1</br>
3:   1 3 3 1</br>
4:  1 4 6 4 1</br>
      .....
      
На вход программе подается число n. Напишите программу, которая возвращает указанную строку треугольника Паскаля в виде списка (нумерация строк начинается с нуля).

Формат входных данных:</br>
На вход программе подается число n (n≥0).

Формат выходных данных:</br>
Программа должна вывести указанную строку треугольника Паскаля в виде списка.

Примечание 1. Решение удобно оформить в виде функции pascal(), которая принимает номер строки и возвращает соответствующую строку треугольника Паскаля.

Примечание 2. Графическая иллюстрация формирования треугольника Паскаля.

In [5]:
from math import factorial 

def pascal(num: int):
    z=[]
    for i in range(num+1):
        z.append(int(factorial(num) / (factorial(i)*factorial(num-i))))
    return z

x=int(input())
print(pascal(x))

[1, 2, 1]


Треугольник Паскаля 2

На вход программе подается натуральное число n. Напишите программу, которая выводит первые n строк треугольника Паскаля.

Формат входных данных:</br>
На вход программе подается число n (n≥1).

Формат выходных данных:</br>
Программа должна вывести первые n строк треугольника Паскаля, каждую на отдельной строке в соответствии с образцом.

In [49]:
from math import factorial
x=int(input())
for i in range(x):
    for j in range(i+1):
        print(factorial(i)//(factorial(j)*factorial(i-j)), end=" ") # nCr = n!/((n-r)!*r!)
    print()

1 
1 1 
1 2 1 
1 3 3 1 
1 4 6 4 1 
1 5 10 10 5 1 


Упаковка дубликатов 🌶️

На вход программе подается строка текста, содержащая символы. Напишите программу, которая упаковывает последовательности одинаковых символов заданной строки в подсписки.

Формат входных данных:</br>
На вход программе подается строка текста, содержащая символы, отделенные символом пробела.

Формат выходных данных:</br>
Программа должна вывести указанный вложенный список.

In [67]:
def groupby(phraze: str):
    from itertools import groupby
    res =[list(v) for k, v in groupby(phraze.split())]
    return res

x=input()
print(groupby(x))

[['a', 'a', 'a'], ['f'], ['g'], ['f', 'f'], ['y', 'y', 'y', 'y', 'y', 'y']]


Разбиение на чанки 🌶️

На вход программе подаются две строки, на одной символы, на другой число n. Из первой строки формируется список.

Реализуйте функцию chunked(), которая принимает на вход список и число, задающее размер чанка (куска), а возвращает список из чанков указанной длины.

Формат входных данных:</br>
На вход программе подается строка текста, содержащая символы, отделенные символом пробела и число n на отдельной строке.

Формат выходных данных:</br>
Программа должна вывести указанный вложенный список.

Примечание. Не забудьте вызвать функцию chunked(), чтобы вывести результат 😀.

In [3]:
def chunked(lst: list, n: int):
    return [lst[i:i + n] for i in range(0, len(lst), n)]

x=input().split()
y=int(input())
print(chunked(x,y))

[['a', 'b'], ['c', 'd'], ['e', 'f']]


Подсписки списка 🌶️🌶️

Подсписок — часть другого списка. Подсписок может содержать один элемент, несколько, и даже ни одного. Например, [1], [2], [3] и [4] — подсписки списка [1, 2, 3, 4]. Список [2, 3] — подсписок списка [1, 2, 3, 4], но список [2, 4] не подсписок списка [1, 2, 3, 4], так как элементы 
2 и 4 во втором списке не смежные. Пустой список — подсписок любого списка. Сам список — подсписок самого себя, то есть список [1, 2, 3, 4] подсписок списка [1, 2, 3, 4].

На вход программе подается строка текста, содержащая символы. Из данной строки формируется список. Напишите программу, которая выводит список, содержащий все возможные подсписки списка, включая пустой список.

Формат входных данных:</br>
На вход программе подается строка текста, содержащая символы, отделенные символом пробела.

Формат выходных данных:</br>
Программа должна вывести указанный список, содержащий все возможные подсписки, включая пустой список в соответствии с примерами.

Примечание. Порядок списков одинаковой длины должен соответствовать порядку их вхождения в основной список.

In [9]:
def sublist(lst:list):
    s_l=[[]]
    for i in range(len(lst)):
        for j in range(len(lst)-i):
            s_l.append(lst[j:j+i+1])
    return s_l


x=input().split()
print(sublist(x))

[[], ['a'], ['b'], ['a', 'b']]


4.4 Матрицы. Часть 1

Что покажет приведенный ниже фрагмент кода?

In [10]:
n = 3
a = [[1, 2, 3],
     [4, 5, 6],
     [7, 8, 9]]

for i in range(n):
    for j in range(n):
        print(a[n - i - 1][n - j - 1], end=' ')
    print()

9 8 7 
6 5 4 
3 2 1 


Что покажет приведенный ниже фрагмент кода?

In [11]:
n = 5
a = [[19, 21, 33, 78, 99], 
     [41, 53, 66, 98, 76], 
     [79, 80, 90, 60, 20],
     [33, 11, 45, 67, 90],
     [45, 67, 12, 98, 23]]

maximum = -1
minimum = 100

for i in range(n):
    if a[i][i] > maximum:
        maximum = a[i][i]
    if a[i][n - i - 1] < minimum:
        minimum = a[i][n - i - 1]
print(minimum + maximum)

101


Вывести матрицу 1

На вход программе подаются два натуральных числа n и m, каждое на отдельной строке — количество строк и столбцов в матрице. Далее вводятся сами элементы матрицы — слова, каждое на отдельной строке; подряд идут элементы сначала первой строки, затем второй, и т.д.

Напишите программу, которая сначала считывает элементы матрицы один за другим, затем выводит их в виде матрицы.

Формат входных данных:</br>
На вход программе подаются два числа n и m — количество строк и столбцов в матрице, далее идут n×m слов, каждое на отдельной строке.

Формат выходных данных:</br>
Программа должна вывести считанную матрицу, разделяя ее элементы одним пробелом.

In [48]:
rows, cols = int(input()), int(input()) 
words=[[input() for word in range(cols)] for i in range(rows)]
for i in range(rows):
    for j in range(cols):
        print(words[i][j], end=' ')
    print()


как дела 
все норм 


Вывести матрицу 2

На вход программе подаются два натуральных числа n и m, каждое на отдельной строке — количество строк и столбцов в матрице. Далее вводятся сами элементы матрицы — слова, каждое на отдельной строке; подряд идут элементы сначала первой строки, затем второй, и т.д.

Напишите программу, которая считывает элементы матрицы один за другим, выводит их в виде матрицы, выводит пустую строку, и снова ту же матрицу, но уже поменяв местами строки со столбцами: первая строка выводится как первый столбец, и так далее.

Формат входных данных:</br>
На вход программе подаются два числа n и m — количество строк и столбцов в матрице, далее идут n×m слов, каждое на отдельной строке.

Формат выходных данных:</br>
Программа должна вывести считанную матрицу, за ней пустую строку, и ту же матрицу, но поменяв местами строки со столбцами. Элементы матрицы разделять одним пробелом.

In [25]:
rows, cols = int(input()), int(input()) 
words=[[input() for word in range(cols)] for i in range(rows)]
for i in range(rows):
    for j in range(cols):
        print(words[i][j], end=' ')
    print()
print()
for i in range(cols):
    for j in range(rows):
        print(words[j][i], end=' ')
    print()

не в бровь 
а в глаз 

не а 
в в 
бровь глаз 


След матрицы

Следом квадратной матрицы называется сумма элементов главной диагонали. Напишите программу, которая выводит след заданной квадратной матрицы.

Формат входных данных:</br>
На вход программе подаётся натуральное число n — количество строк и столбцов в матрице, затем элементы матрицы (целые числа) построчно через пробел.

Формат выходных данных:</br>
Программа должна вывести одно число — след заданной матрицы.

In [69]:
x=int(input())
nums=[list(map(int, input().split())) for i in range(x)] #list необходим для формирования именно списко через ф-цию map, а не объекта
sums=0
for i in range(x):
    for j in range(x):
        if i==j:
            sums+=nums[i][j] 
print(sum)

0


Больше среднего

Напишите программу, которая выводит количество элементов квадратной матрицы в каждой строке, больших среднего арифметического элементов данной строки.

Формат входных данных:</br>
На вход программе подаётся натуральное число n — количество строк и столбцов в матрице, затем элементы матрицы (целые числа) построчно через пробел.

Формат выходных данных:</br>
Программа должна вывести n чисел — для каждой строки количество элементов матрицы, больших среднего арифметического элементов данной строки.

In [8]:
x=int(input())
nums=[list(map(int, input().split())) for i in range(x)]
count=0
for i in range(x):
    for j in range(x):
        if nums[i][j]>sum(nums[i])/x:
                count+=1
    print(count)
    count=0

1
1


Максимальный в области 1

Напишите программу, которая выводит максимальный элемент в заштрихованной области квадратной матрицы.

Формат входных данных:</br>
На вход программе подаётся натуральное число n — количество строк и столбцов в матрице, затем элементы матрицы (целые числа) построчно через пробел.

Формат выходных данных:</br>
Программа должна вывести одно число — максимальный элемент в заштрихованной области квадратной матрицы.

Примечание. Элементы главной диагонали также учитываются.

In [10]:
x=int(input())
nums=[list(map(int, input().split())) for i in range(x)]
total=[]
for i in range(x):
    for j in range(x):
        if i>=j:
            total.append(nums[i][j])
print(max(total))


5
6
99
5


Максимальный в области 2 🌶️

Напишите программу, которая выводит максимальный элемент в заштрихованной области квадратной матрицы.

Формат входных данных:</br>
На вход программе подаётся натуральное число n — количество строк и столбцов в матрице, затем элементы матрицы (целые числа) построчно через пробел.

Формат выходных данных:</br>
Программа должна вывести одно число — максимальный элемент в заштрихованной области квадратной матрицы.

Примечание. Элементы диагоналей также учитываются.

In [15]:
x=int(input())
nums=[list(map(int, input().split())) for i in range(x)]
total=[]
for i in range(x):
    for j in range(x):
        if i >= j and i <= x-1-j or i <= j and i >= x-1-j: 
            total.append(nums[i][j])
print(max(total))


7


Суммы четвертей

Квадратная матрица разбивается на четыре четверти, ограниченные главной и побочной диагоналями: верхнюю, нижнюю, левую и правую.

Напишите программу, которая вычисляет сумму элементов: верхней четверти; правой четверти; нижней четверти; левой четверти.

Формат входных данных:</br>
На вход программе подаётся натуральное число n — количество строк и столбцов в матрице, затем элементы матрицы (целые числа) построчно через пробел.

Формат выходных данных:</br>
Программа должна вывести текст в соответствии с условием задачи.

Примечание. Элементы диагоналей не учитываются.

In [6]:
x=int(input())
nums=[list(map(int, input().split())) for i in range(x)]

first=sum([nums[i][j] for i in range(x) for j in range(x) if x - 1 - j > i < j])
second=sum([nums[i][j] for i in range(x) for j in range(x) if x - 1 - j < i < j])
third=sum([nums[i][j] for i in range(x) for j in range(x) if x - 1 - j < i > j])
fourth=sum([nums[i][j] for i in range(x) for j in range(x) if x - 1 - j > i > j])

print(f'Верхняя четверть: {first}\nПравая четверть: {second}\nНижняя четверть: {third}\nЛевая четверть: {fourth}')

Верхняя четверть: 13
Правая четверть: 1
Нижняя четверть: 4
Левая четверть: 65


4.5 Матрицы. Часть 2

Таблица умножения

На вход программе подаются два натуральных числа n и m — количество строк и столбцов в матрице. Создайте матрицу mult размером n×m и заполните её таблицей умножения по формуле mult[i][j] = i * j.

Формат входных данных:</br>
На вход программе на разных строках подаются два числа n и m — количество строк и столбцов в матрице.

Формат выходных данных:</br>
Программа должна вывести таблицу умножения отводя на вывод каждого числа ровно 3 символа (для этого используйте строковый метод ljust()).

In [11]:
x, y=int(input()), int(input())
matrix=[[i*j for i in range(y)] for j in range(x)]
for r in range(x):
    for c in range(y):
        print(str(matrix[r][c]).ljust(3), end='')
    print()

0  0  0  0  0  0  
0  1  2  3  4  5  
0  2  4  6  8  10 
0  3  6  9  12 15 


Максимум в таблице

На вход программе подаются два натуральных числа n и m — количество строк и столбцов в матрице, затем n строк по m целых чисел в каждой, отделенных символом пробела.

Напишите программу, которая находит индексы (строку и столбец) первого вхождения максимального элемента.

Формат входных данных:</br>
На вход программе на разных строках подаются два числа n и m — количество строк и столбцов в матрице, затем сами элементы матрицы построчно через пробел.

Формат выходных данных:</br>
Программа должна вывести два числа: номер строки и номер столбца, в которых стоит наибольший элемент таблицы. Если таких элементов несколько, то выводится тот, у которого меньше номер строки, а если номера строк равны то тот, у которого меньше номер столбца.

Примечание. Считайте, что нумерация строк и столбцов начинается с нуля.

In [41]:
x, y =int(input()), int(input())
matrix=[list(map(int, input().split())) for i in range(x)]
maximum=matrix[0][0]
a,b=0,0
for i in range(x):
    for j in range(y):
        if matrix[i][j]>maximum:
            maximum=matrix[i][j]
            a=i
            b=j
print(a, b)

1 1


Обмен столбцов

Напишите программу, которая меняет местами столбцы в матрице.

Формат входных данных:</br>
На вход программе на разных строках подаются два натуральных числа n и m — количество строк и столбцов в матрице, затем элементы матрицы построчно через пробел, затем числа i и j — номера столбцов, подлежащих обмену.

Формат выходных данных:</br>
Программа должна вывести указанную таблицу с замененными столбцами.

In [16]:
row, col=int(input()), int(input())
matrix=[list(map(int, input().split())) for i in range(row)]

change=[int(i) for i in input().split()]

for i in range(row):
    for j in range(col):
        matrix[i][change[0]], matrix[i][change[1]]=matrix[i][change[1]], matrix[i][change[0]]
        if j==0:
            print(*matrix[i], end='\n' )

2 1 3
2 1 3
2 1 3


Симметричная матрица

Напишите программу, которая проверяет симметричность квадратной матрицы относительно главной диагонали.

Формат входных данных:</br>
На вход программе подаётся натуральное число n — количество строк и столбцов в матрице, затем элементы матрицы построчно через пробел.

Формат выходных данных:</br>
Программа должна вывести YES, если матрица симметрична относительно главной диагонали, и слово NO в противном случае.

In [45]:
def compare(lst: list):
    zipped_rows=zip(*lst)
    lst_t=[list(row) for row in zipped_rows]
    if lst==lst_t:
        return 'YES'
    else:
        return 'NO'
    
matrix=[list(map(int, input().split())) for i in range(int(input()))]

print(compare(matrix))


YES


In [41]:
def compare(lst: list):
    import pymatrix
    lst=pymatrix.matrix(lst)
    lst_t=lst.trans()
    if lst==lst_t:
        return 'YES'
    else:
        return 'NO'
    
matrix=[list(map(int, input().split())) for i in range(int(input()))]

print(compare(matrix))

YES


Обмен диагоналей

Дана квадратная матрица чисел. Напишите программу, которая меняет местами элементы, стоящие на главной и побочной диагонали, при этом каждый элемент должен остаться в том же столбце (то есть в каждом столбце нужно поменять местами элемент на главной диагонали и на побочной диагонали).

Формат входных данных:</br>
На вход программе подаётся натуральное число n — количество строк и столбцов в матрице, затем элементы матрицы построчно через пробел.

Формат выходных данных:</br>
Программа должна вывести матрицу с элементами главной и побочной диагонали, поменявшимися своими местами.

In [2]:
x=int(input())
matrix=[list(map(int, input().split())) for i in range(x)]

for j in range(x):
    matrix[j][j], matrix[x-1-j][j]=matrix[x-1-j][j], matrix[j][j]

for k in range(x):
    print(*matrix[k])

7 2 9
4 5 6
1 8 3


Зеркальное отображение

Дана квадратная матрица чисел. Напишите программу, которая зеркально отображает её элементы относительно горизонтальной оси симметрии.

Формат входных данных:</br>
На вход программе подаётся натуральное число n — количество строк и столбцов в матрице, затем элементы матрицы построчно через пробел.

Формат выходных данных:</br>
Программа должна вывести матрицу в которой зеркально отображены элементы относительно горизонтальной оси симметрии.

In [6]:
x=int(input())
matrix=[list(map(int, input().split())) for i in range(x)]

for j in reversed(range(x)):
    print(*matrix[j])

7 8 9
4 5 6
1 2 3


Поворот матрицы

Напишите программу, которая поворачивает квадратную матрицу чисел на 90∘ по часовой стрелке.

Формат входных данных:</br>
На вход программе подаётся натуральное число n — количество строк и столбцов в матрице, затем элементы матрицы построчно через пробел.

Формат выходных данных:</br>
Программа должна вывести результат на экран, числа должны быть разделены одним пробелом.

In [21]:
x=int(input())
matrix=[list(map(int, input().split())) for i in range(x)]

matrix=tuple(zip(*matrix[::-1]))

for j in range(x):
    print(*matrix[j])


7 4 1
8 5 2
9 6 3


Ходы коня

На шахматной доске 8×8 стоит конь. Напишите программу, которая отмечает положение коня на доске и все клетки, которые бьет конь. Клетку, где стоит конь, отметьте английской буквой N, клетки, которые бьет конь, отметьте символами * остальные клетки заполните точками.

Формат входных данных:</br>
На вход программе подаются координаты коня на шахматной доске в шахматной нотации (то есть в виде e4, где сначала записывается номер столбца (буква от a до h, слева направо), затем номеру строки (цифра от 1 до 8, снизу вверх)).

Формат выходных данных:</br>
Программа должна вывести на экран изображение доски, разделяя элементы пробелами.

In [3]:
x,y=input()
n=8
matrix=[['.']*n for _ in range(n)]
y=n-int(y)
x=ord(x)-97
matrix[y][x]='N'

for i in range(n):
    for j in range(n):
        if abs(i-y)*abs(j-x)==2:
            matrix[i][j]='*'

for k in range(n):
    print(*matrix[k])

. . . . . . . .
. . . . . . . .
. . . . . . . .
. . . . * . * .
. . . * . . . *
. . . . . N . .
. . . * . . . *
. . . . * . * .


Магический квадрат 🌶️

Магическим квадратом порядка n называется квадратная таблица размера n×n, составленная из всех чисел 1,2,3,…,n^2 так, что суммы по каждому столбцу, каждой строке и каждой из двух диагоналей равны между собой. Напишите программу, которая проверяет, является ли заданная квадратная матрица магическим квадратом.

Формат входных данных:</br>
На вход программе подаётся натуральное число n — количество строк и столбцов в матрице, затем элементы матрицы: n строк, по n чисел в каждой, разделённые пробелами.

Формат выходных данных:</br>
Программа должна вывести слово YES, если матрица является магическим квадратом, и слово NO в противном случае.

In [ ]:
x=int(input())
matrix=[list(map(int, input().split())) for i in range(x)]
digits=[i for i in range(1, x**2+1)]

d1,d2=0,0

for j in range(x):
    stolb, stroka=0,0
    for k in range(x):
        stolb+=matrix[k][j]
        stroka+=matrix[j][k]
        if matrix[j][k] in digits:
            digits.remove(matrix[j][k])

    d1+=matrix[j][j]
    d2+=matrix[j][x-j-1]
    if stolb!=stroka:
        break

if stolb==stroka==d1==d2 and digits==[]:
    print('YES')
else:
    print('NO')

4.6 Матрицы. Часть 3

Шахматная доска
На вход программе подаются два натуральных числа n и m. Напишите программу для создания матрицы размером n×m, заполнив её символами . и * в шахматном порядке. В левом верхнем углу должна стоять точка. Выведите полученную матрицу на экран, разделяя элементы пробелами.

Формат входных данных:</br>
На вход программе на одной строке подаются два натуральных числа n и m — количество строк и столбцов в матрице.

Формат выходных данных:</br>
Программа должна вывести матрицу, описанную в условии задачи.

In [18]:
row, col=map(int,input().split())
matrix=[['0']*col for _ in range(row)]

for i in range(row):
    for j in range(col):
        if (i%2==0 and j%2==0) or (i%2!=0 and j%2!=0):
            matrix[i][j]='.'
        if (i%2==0 and j%2!=0) or (i%2!=0 and j%2==0):
            matrix[i][j]='*' 

for k in range(row):
    print(*matrix[k])

. * . *
* . * .
. * . *


Побочная диагональ

На вход программе подается натуральное число n. Напишите программу, которая создает матрицу размером n×n и заполняет её по следующему правилу:</br>
- числа на побочной диагонали равны 1;</br>
- числа, стоящие выше этой диагонали, равны 0;</br>
- числа, стоящие ниже этой диагонали, равны 2.</br>

Полученную матрицу выведите на экран. Числа в строке разделяйте одним пробелом.

Формат входных данных:</br>
На вход программе подается натуральное число n — количество строк и столбцов в матрице.

Формат выходных данных:</br>
Программа должна вывести матрицу в соответствии с условием задачи.

Примечание. Побочная диагональ — это диагональ, идущая из правого верхнего в левый нижний угол матрицы.

In [39]:
x=int(input())
matrix=[['0']*x for _ in range(x)]

for i in range(x):
    for j in range(x):
        if i>x-1-j:
            matrix[i][j]=2     
        if i==x-1-j:
            matrix[i][j]=1

for p in range(x):
    print(*matrix[p])

0 0 0 1
0 0 1 2
0 1 2 2
1 2 2 2


Заполнение 1

На вход программе подаются два натуральных числа n и m. Напишите программу, которая создает матрицу размером n×m и заполняет её числами от 1 до n⋅m в соответствии с образцом.

Формат входных данных:</br>
На вход программе на одной строке подаются два натуральных числа n и m — количество строк и столбцов в матрице.

Формат выходных данных:</br>
Программа должна вывести матрицу в соответствии с образцом.

Примечание. Для вывода элементов матрицы как в примерах, отводите ровно 3 символа на каждый элемент. Для этого используйте строковый метод ljust(). Можно обойтись и без ljust(), система примет и такое решение 😇

In [5]:
row, col=map(int,input().split())
matrix=[[i+j for i in range(col)]  for j in range(row)]

count=1
for k in range(row):
    for l in range(col):
        matrix[k][l]=count
        count+=1

for m in range(row):
    for n in range(col):       
        print(str(matrix[m][n]).ljust(3), end='')
    print()

1  2  3  4  
5  6  7  8  
9  10 11 12 


Заполнение 2

На вход программе подаются два натуральных числа n и m. Напишите программу, которая создает матрицу размером n×m заполнив её в соответствии с образцом.

Формат входных данных:</br>
На вход программе на одной строке подаются два натуральных числа n и m — количество строк и столбцов в матрице.

Формат выходных данных:</br>
Программа должна вывести указанную матрицу в соответствии с образцом.

Примечание. Для вывода элементов матрицы как в примерах, отводите ровно 3 символа на каждый элемент. Для этого используйте строковый метод ljust(). Можно обойтись и без ljust(), система примет и такое решение 😇

In [40]:
row, col=map(int,input().split())
matrix=[[i+j for i in range(col)]  for j in range(row)]

count=1
for k in range(col):
    for l in range(row):
        matrix[l][k]=count
        count+=1

for m in range(row):
    for n in range(col):       
        print(str(matrix[m][n]).ljust(3), end='')
    print()

1  4  7  10 
2  5  8  11 
3  6  9  12 


Заполнение 3
На вход программе подается натуральное число n. Напишите программу, которая создает матрицу размером n×n заполнив её в соответствии с образцом.

Формат входных данных:</br>
На вход программе подается натуральное число n — количество строк и столбцов в матрице.

Формат выходных данных:</br>
Программа должна вывести указанную матрицу в соответствии с образцом: разместить единицы на главной и побочной диагоналях, остальные позиции матрицы заполнить нулями.

Примечание. Для вывода элементов матрицы как в примерах, отводите ровно 3 символа на каждый элемент. Для этого используйте строковый метод ljust(). Можно обойтись и без ljust(), система примет и такое решение 😇

In [69]:
x=int(input())
matrix=[[0]*x for _ in range(x)]

for k in range(x):
    for l in range(x):
        if k==l or k==x-1-l:
            matrix[k][l]=1
        

for p in range(x):
    print(*matrix[p])

1 0 0 0 1
0 1 0 1 0
0 0 1 0 0
0 1 0 1 0
1 0 0 0 1


Заполнение 4

На вход программе подается натуральное число n. Напишите программу, которая создает матрицу размером n×n заполнив её в соответствии с образцом.

Формат входных данных:</br>
На вход программе подается натуральное число n — количество строк и столбцов в матрице.

Формат выходных данных:</br>
Программа должна вывести указанную матрицу в соответствии с образцом.

Примечание. Для вывода элементов матрицы как в примерах, отводите ровно 3 символа на каждый элемент. Для этого используйте строковый метод ljust(). Можно обойтись и без ljust(), система примет и такое решение 😇

In [72]:
x=int(input())
matrix=[[1]*x for _ in range(x)]

for k in range(x):
    for l in range(x):
        if k>l and k<x-1-l or k<l and k>x-1-l:
            matrix[k][l]=0
        
for p in range(x):
    print(*matrix[p])

1 1 1 1 1
0 1 1 1 0
0 0 1 0 0
0 1 1 1 0
1 1 1 1 1


Заполнение 5 🌶️

На вход программе подаются два натуральных числа n и m. Напишите программу, которая создает матрицу размером n×m заполнив её в соответствии с образцом.

Формат входных данных:</br>
На вход программе на одной строке подаются два натуральных числа n и m — количество строк и столбцов в матрице.

Формат выходных данных:</br>
Программа должна вывести указанную матрицу в соответствии с образцом.

Примечание. Для вывода элементов матрицы как в примерах, отводите ровно 3 символа на каждый элемент. Для этого используйте строковый метод ljust(). Можно обойтись и без ljust(), система примет и такое решение 😇

In [14]:
row, col=map(int,input().split())
tmp=[i for i in range(1,col+1)]
matrix=[]

for j in range(row):
    matrix.append(tmp)
    tmp=tmp[1:]+[tmp[0]]


for m in range(row):
    for n in range(col):       
        print(str(matrix[m][n]).ljust(3), end='')
    print()



1  2  3  4  5  
2  3  4  5  1  
3  4  5  1  2  
4  5  1  2  3  
5  1  2  3  4  


Заполнение змейкой

На вход программе подаются два натуральных числа n и m. Напишите программу, которая создает матрицу размером n×m заполнив её "змейкой" в соответствии с образцом.

Формат входных данных:</br>
На вход программе на одной строке подаются два натуральных числа n и m — количество строк и столбцов в матрице.

Формат выходных данных:</br>
Программа должна вывести указанную матрицу в соответствии с образцом.

Примечание. Для вывода элементов матрицы как в примерах, отводите ровно 3 символа на каждый элемент. Для этого используйте строковый метод ljust(). Можно обойтись и без ljust(), система примет и такое решение 😇

In [4]:
row, col=map(int,input().split())
matrix=[[i+j for i in range(col)]  for j in range(row)]

count=1
for k in range(row):
    if k%2==0:
        for l in range(col):
            matrix[k][l]=count
            count+=1
    else:
        for l in reversed(range(col)):
            matrix[k][l]=count
            count+=1
        
for m in range(row):
    for n in range(col):       
        print(str(matrix[m][n]).ljust(3), end='')
    print()

1  2  3  4  5  
10 9  8  7  6  
11 12 13 14 15 


Заполнение диагоналями 🌶️

На вход программе подаются два натуральных числа n и m. Напишите программу, которая создает матрицу размером n×m заполнив её "диагоналями" в соответствии с образцом.

Формат входных данных:</br>
На вход программе на одной строке подаются два натуральных числа n и m — количество строк и столбцов в матрице.

Формат выходных данных:</br>
Программа должна вывести указанную матрицу в соответствии с образцом.

Примечание. Для вывода элементов матрицы как в примерах, отводите ровно 3 символа на каждый элемент. Для этого используйте строковый метод ljust(). Можно обойтись и без ljust(), система примет и такое решение 😇

In [22]:
row, col=map(int,input().split())
matrix=[[i+j for i in range(col)]  for j in range(row)]

count=1
for k in range(row*col):
    for l in range(row):
        for m in range(col):
            if l+m==k:
                matrix[l][m]=count
                count+=1
        
for m in range(row):
    for n in range(col):       
        print(str(matrix[m][n]).ljust(3), end='')
    print()

1  2  4  7  10 
3  5  8  11 13 
6  9  12 14 15 


Заполнение спиралью 😈😈

На вход программе подаются два натуральных числа n и m. Напишите программу, которая создает матрицу размером n×m заполнив её "спиралью" в соответствии с образцом.

Формат входных данных:</br>
На вход программе на одной строке подаются два натуральных числа n и m — количество строк и столбцов в матрице.

Формат выходных данных:</br>
Программа должна вывести матрицу в соответствии образцом.

Примечание. Для вывода элементов матрицы как в примерах, отводите ровно 3 символа на каждый элемент. Для этого используйте строковый метод ljust(). Можно обойтись и без ljust(), система примет и такое решение 😇

In [3]:
row, col=map(int,input().split())
matrix=[]
for _ in range(row):
    tmp=[0 for e in range(col)]
    matrix.append(tmp)

x,y=0,0
d_x,d_y=0,1
matrix[0][0]=1
count=2

while count<=row*col:
    if 0<=x+d_x<=row-1 and 0<=y+d_y<=col-1 and matrix[x+d_x][y+d_y]==0:
        matrix[x+d_x][y+d_y]=count
        count+=1
        x+=d_x
        y+=d_y
    else:
        if d_y==1:
            d_y=0
            d_x=1
        elif d_x==1:
            d_x=0
            d_y=-1
        elif d_y==-1:
            d_y=0
            d_x=-1
        elif d_x==-1:
            d_x=0
            d_y=1

for m in range(row):
    for n in range(col):       
        print(str(matrix[m][n]).ljust(3), end='')
    print()

1  2  3  4  5  
14 15 16 17 6  
13 20 19 18 7  
12 11 10 9  8  


4.7 Операции над матрицами в математике

Найти сумму матриц А и Б.

In [4]:
import numpy as np
a=np.array([[1,1,1], [2,2,2], [3,3,3]])
b=np.array([[1,2,3], [4,5,6],[7,8,9]])
print(a+b)

[[ 2  3  4]
 [ 6  7  8]
 [10 11 12]]


Найти произведение матрицы B и k.


In [5]:
import numpy as np
b=np.array([[1,2,3], [4,5,6], [7,8,9]])
k=3
print(b*k)

[[ 3  6  9]
 [12 15 18]
 [21 24 27]]


Найти произведение матриц A и B.

In [14]:
import numpy as np
a=np.array([[1,1,1], [2,2,2], [3,3,3]])
b=np.array([[1,2,3], [4,5,6], [7,8,9]])
print(np.dot(a,b))

[[12 15 18]
 [24 30 36]
 [36 45 54]]


Найти произведение матриц A и B.

In [15]:
import numpy as np
a=np.array([[1,-1,0], [3,-4,2]])
b=np.array([[1,2], [3,4], [5,6]])
print(np.dot(a,b))

[[-2 -2]
 [ 1  2]]


Для матрицы А= [[1, 0], [4, 1]] найти А^25.

In [17]:
import numpy as np
a=np.array([[1,0], [4,1]])
a=np.matrix(a)
print(a**25)

[[  1   0]
 [100   1]]


Сложение матриц

Напишите программу для вычисления суммы двух матриц.

Формат входных данных:</br>
На вход программе подаются два натуральных числа n и m — количество строк и столбцов в матрицах, затем элементы первой матрицы, затем пустая строка, далее следуют элементы второй матрицы.

Формат выходных данных:</br>
Программа должна вывести результирующую матрицу, разделяя элементы символом пробела.

In [21]:
import numpy as np
x,y=map(int,input().split())
matrix1=[list(map(int, input().split())) for i in range(x)]
null=input()
matrix2=[list(map(int, input().split())) for i in range(x)]
sum=np.array(matrix1)+np.array(matrix2)

for m in range(x):
    for n in range(y):       
        print(str(sum[m][n]).ljust(3), end='')
    print()

4  4  4  6  
6  9  8  4  


Умножение матриц 🌶️

Напишите программу, которая перемножает две матрицы.

Формат входных данных:</br>
На вход программе подаются два натуральных числа n и m — количество строк и столбцов в первой матрице, затем элементы первой матрицы, затем пустая строка. Далее следуют числа m и k — количество строк и столбцов второй матрицы затем элементы второй матрицы.

Формат выходных данных:</br>
Программа должна вывести результирующую матрицу, разделяя элементы символом пробела.

In [ ]:
import numpy as np
x,y=map(int,input().split())
matrix1=np.array([list(map(int, input().split())) for i in range(x)])
null=input()
x1,y1=map(int,input().split())
matrix2=np.array([list(map(int, input().split())) for j in range(x1)])
matrix=np.dot(matrix1,matrix2)

for p in range(len(matrix)):
    print(*matrix[p])

Возведение матрицы в степень 🌶️

Напишите программу, которая возводит квадратную матрицу в m-ую степень.

Формат входных данных:</br>
На вход программе подаётся натуральное число n — количество строк и столбцов в матрице, затем элементы матрицы, затем натуральное число m.

Формат выходных данных:</br>
Программа должна вывести результирующую матрицу, разделяя элементы символом пробела.

In [ ]:
import numpy as np
from numpy.linalg import matrix_power

matrix=np.array([list(map(int, input().split())) for i in range(int(input()))])
matrix=matrix_power(matrix, int(input()))

for p in range(len(matrix)):
    print(*matrix[p])